//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowService1.textModService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="textModService.ITextModService")]
    public interface ITextModService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextModService/ChangeTest", ReplyAction="http://tempuri.org/ITextModService/ChangeTestResponse")]
        WorkflowService1.textModService.ChangeTestResponse ChangeTest(WorkflowService1.textModService.ChangeTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextModService/ChangeTest", ReplyAction="http://tempuri.org/ITextModService/ChangeTestResponse")]
        System.Threading.Tasks.Task<WorkflowService1.textModService.ChangeTestResponse> ChangeTestAsync(WorkflowService1.textModService.ChangeTestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeTest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangeTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string text;
        
        public ChangeTestRequest() {
        }
        
        public ChangeTestRequest(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeTestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangeTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ChangeTestResult;
        
        public ChangeTestResponse() {
        }
        
        public ChangeTestResponse(string ChangeTestResult) {
            this.ChangeTestResult = ChangeTestResult;
        }
    }
}
